apiRules:
- exclude:
      hasAttribute:
            uid: System.ComponentModel.EditorBrowsableAttribute
- exclude:
      uidRegex: ^IronOcr.Languages$
- exclude:
      uidRegex: ^IronOcr.BarcodeReaderSafety$      
- exclude:      
      uidRegex: ^IronXL.Xml$
- exclude:      
      uidRegex: ^IronXL.Xml.*$
- exclude:
   uidRegex: ^IronPdf.ChromeHttpLoginCredentials.CustomHttpHeaders$
- exclude:
   uidRegex: ^IronPdf.ChromeHttpLoginCredentials.CustomPostFiles$
- exclude:
   uidRegex: ^IronPdf.ChromeHttpLoginCredentials.CustomPostVariables$
- exclude:
   uidRegex: ^IronPdf.ChromeHttpLoginCredentials.LoginFormPostVariables$
- exclude:
   uidRegex: ^IronPdf.ChromeHttpLoginCredentials.LoginFormUrl$
- exclude:
   uidRegex: ^IronPdf.ChromeHttpLoginCredentials.Proxy$
- exclude:
   uidRegex: ^IronPdf.ChromeHttpLoginCredentials.UserAgent$
- exclude:
   uidRegex: ^IronPdf.ChromePdfRenderOptions.FitToPaper$
- exclude:
   uidRegex: ^IronPdf.ChromePdfRenderOptions.JpegQuality$
- exclude:
   uidRegex: ^IronPdf.ChromePdfRenderOptions.DPI$
- exclude:
   uidRegex: ^IronPdf.ChromePdfRenderOptions.PdfPaperOrientation$
- exclude:
   uidRegex: ^IronPdf.Installation.LegacyIIS$
- exclude:
   uidRegex: ^IronPdf.ImageBehavior$
- exclude:
   uidRegex: ^IronPdf.ImageType$
- exclude:
   uidRegex: ^IronPdf.PageOrientation$
- exclude:
   uidRegex: ^IronPdf.HtmlStamp$
- exclude:
   uidRegex: ^IronPdf.PdfBookMark$
- exclude:
   uidRegex: ^IronPdf.PdfDocument.TextAnnotation$
- exclude:
   uidRegex: ^IronPdf.PdfDocument.PositionOptions$
- exclude:
   uidRegex: ^IronPdf.PdfDocument.PdfSecuritySettings$
- exclude:
   uidRegex: ^IronPdf.PdfDocument.PdfEditSecurity$
- exclude:
   uidRegex: ^IronPdf.PdfDocument.PdfPrintSecrity$
- exclude:
   uidRegex: ^IronPdf.PdfDocument.WaterMarkLocation$
- exclude:
   uidRegex: ^IronPdf.PdfDocument.PdfCustomMetadataProperties$
- exclude:
   uidRegex: ^IronPdf.PDFHeaderFooter$
- exclude:
   uidRegex: ^IronPdf.PdfOutline$
- exclude:
   uidRegex: ^IronPdf.PdfPage$
- exclude:
   uidRegex: ^IronPdf.PdfPrintOptions$
- exclude:
   uidRegex: ^IronPdf.Util$
- exclude:
   uidRegex: ^IronPdf.PdfSignature$
- exclude:
   uidRegex: ^IronPdf.PdfPrintDocument.PageSettings$
- exclude:
   uidRegex: ^IronPdf.PrinterSettings$
- exclude:
   uidRegex: ^IronPdf.TextHeaderFooter.FontFamily$
- exclude:
   uidRegex: ^IronPdf.HtmlToPdf$
- exclude:
   uidRegex: ^IronPdfEngine.Proto$
- exclude:
   uidRegex: ^Ironpdfengineproto$

